### ISSUE TITLE
Creation Date

### ISSUE THREAD

**Issue by shoaibhassan1** [dragosrobertn/KNContacts#2]
Thankyou for a wonderfull wraper, is there a way to filter contact using their creation date in device.
Thanks in advance.

**Comment by dragosrobertn** [comment]
Hi, 
Unfortunately this information is not exposed by the Contacts framework, but you could try to subscribe to the [Contacts History](https://developer.apple.com/documentation/contacts/cnchangehistoryfetchrequest) events - it's a public but undocumented API. 
Apologies.
